=== craig344/webtech/XML/election.dtd
<!ELEMENT election (parties, candidates, constituencies, performance)>

<!ELEMENT parties (party+)>
<!ELEMENT party (party_name, party_symbol)>
<!ATTLIST party pid ID #REQUIRED>
<!ELEMENT party_name (#PCDATA)>
<!ELEMENT party_symbol (#PCDATA)>

<!ELEMENT candidates (candidate+)>
<!ELEMENT candidate (candidate_name, candidate_age)>
<!ATTLIST candidate cid ID #REQUIRED>
<!ELEMENT candidate_name (#PCDATA)>
<!ELEMENT candidate_age (#PCDATA)>

<!ELEMENT constituencies (constituency+)>
<!ELEMENT constituency (constituency_name, count)>
<!ATTLIST constituency coid ID #REQUIRED>
<!ELEMENT constituency_name (#PCDATA)>
<!ELEMENT count (#PCDATA)>

<!ELEMENT performance (constituency_data+)>
<!ELEMENT constituency_data (party_data+)>
<!ATTLIST constituency_data coid IDREF #REQUIRED>
<!ELEMENT party_data EMPTY>
<!ATTLIST party_data 
pid IDREF #REQUIRED
cid IDREF #REQUIRED
votes CDATA #REQUIRED>

=== craig344/webtech/XML/election.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE election SYSTEM "election.dtd">
<election>
  <parties>
    <party pid = "p1">
        <party_name>Congress</party_name>
        <party_symbol>Hand</party_symbol>
    </party>
    <party pid = "p2">
        <party_name>BJP</party_name>
        <party_symbol>lotus</party_symbol>
    </party>
    <party pid = "p3">
        <party_name>Aam Aadmi Party</party_name>
        <party_symbol>broom</party_symbol>
    </party>
  </parties>
  <candidates>
    <candidate cid="c1">
        <candidate_name>Craig</candidate_name>
        <candidate_age>24</candidate_age>
    </candidate>
    <candidate cid="c2">
        <candidate_name>Harshad</candidate_name>
        <candidate_age>29</candidate_age>
    </candidate>
    <candidate cid="c3">
        <candidate_name>Digvijay</candidate_name>
        <candidate_age>21</candidate_age>
    </candidate>
    <candidate cid="c4">
        <candidate_name>Jeff</candidate_name>
        <candidate_age>22</candidate_age>
    </candidate>
  </candidates>
  <constituencies>
    <constituency coid = "co1">
        <constituency_name>Salcete</constituency_name>
        <count>500</count>
    </constituency>
    <constituency coid = "co2">
        <constituency_name>Bardez</constituency_name>
        <count>500</count>
    </constituency>
    <constituency coid = "co3">
        <constituency_name>Pernem</constituency_name>
        <count>500</count>
    </constituency>
  </constituencies>
  <performance>
    <constituency_data coid = "co1">
        <party_data pid = "p1" cid = "c1" votes = "100"/>
        <party_data pid = "p2" cid = "c2" votes = "150"/>
        <party_data pid = "p3" cid = "c3" votes = "250"/>
    </constituency_data>
    </performance>
</election>
